version: "3"
services:
  localstack:
    container_name: 'localstack_main'
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "${PORT_WEB_UI-8000}:${PORT_WEB_UI-8080}"
    environment:
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - PORT_WEB_UI=8080
      - HOSTNAME_EXTERNAL=localstack
      - AWS_ACCESS_KEY_ID=temp
      - AWS_SECRET_ACCESS_KEY=temp
      - LAMBDA_DOCKER_NETWORK=host
      - LAMBDA_EXECUTOR=docker
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"